name: snake

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

permissions:
  contents: write   # ✅ IMPORTANT FIX

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate snake
        uses: Platane/snk@v3
        with:
          github_user_name: PrimeSumit
          outputs: dist/snake.svg

      - name: Push snake
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          branch: output
          commit_message: "generate snake"
