name: snake

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate snake
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark

      - name: Push to output branch
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

          git clone --depth=1 https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} temp
          cd temp
          git checkout --orphan output
          rm -rf *
          cp -r ../dist/* .
          git add .
          git commit -m "update snake"
          git push origin output --force
